name: EscribeGT
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.2
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  firebase_database: ^12.1.3
  cloud_firestore: ^6.1.2
  flutter_plugin_android_lifecycle: ^2.0.22
  path_provider_android: ^2.2.0
  image_picker_android: ^0.8.9
  scribble: 0.10.0+1
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true